# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gymDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gymName', models.CharField(max_length=100)),
                ('gymCity', models.CharField(max_length=100)),
                ('gymAddress', models.TextField()),
                ('gymPincode', models.IntegerField(max_length=9)),
                ('gymRegistrationDate', models.DateTimeField(verbose_name='Registration Date')),
                ('gymNumber', models.IntegerField(max_length=9)),
            ],
        ),
    ]
