# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='gymPassword',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='gymUsername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
