# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170620_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='gymdetails',
            name='gymNumber',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
