# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gymDetails',
            fields=[
                ('gymName', models.CharField(max_length=100)),
                ('gymCity', models.CharField(max_length=100)),
                ('gymAddress', models.TextField()),
                ('gymPincode', models.IntegerField(max_length=9)),
                ('gymRegistrationDate', models.DateTimeField(verbose_name='Registration Date')),
                ('gymNumber', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('gymUsername', models.CharField(max_length=100)),
                ('gymPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='memberDetails',
            fields=[
                ('memberName', models.CharField(max_length=100)),
                ('memberCity', models.CharField(max_length=100)),
                ('memberAddress', models.TextField(blank=True)),
                ('memberPincode', models.IntegerField(blank=True, max_length=9)),
                ('memberContactNumber', models.IntegerField(max_length=14)),
                ('memberEmergencyNumber', models.IntegerField(blank=True, max_length=14)),
                ('memberEmail', models.CharField(max_length=100)),
                ('memberRegistrationDate', models.DateTimeField(verbose_name='Registration Date')),
                ('memberNumber', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('memberStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
