# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0002_gymdetails_gymregistrationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='memberGymNumber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appRegistration.gymDetails'),
            preserve_default=False,
        ),
    ]
