# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appRegistration', '0003_memberdetails_membergymnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='gymUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
