# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0004_gymdetails_gymuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=100)),
                ('planDuration', models.IntegerField(max_length=4)),
                ('planPrice', models.IntegerField(max_length=9)),
                ('planDescription', models.CharField(max_length=300)),
                ('planGymNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRegistration.gymDetails')),
            ],
        ),
    ]
