# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0007_memberdetails_membergender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='staffGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
