# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0008_staffdetails_staffgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='memberPlan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberPlanActivationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Plan Activation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberPlandExpiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Plan Expiry Date'),
            preserve_default=False,
        ),
    ]
