# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0009_auto_20170802_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymdetails',
            old_name='gymPassword',
            new_name='gymType',
        ),
        migrations.RemoveField(
            model_name='gymdetails',
            name='gymUsername',
        ),
        migrations.AddField(
            model_name='gymplans',
            name='planStatus',
            field=models.BooleanField(default=True),
        ),
    ]
