# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0014_auto_20170807_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='gymContactNumber',
            field=models.IntegerField(default=1, max_length=14, verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymdetails',
            name='gymImage',
            field=models.ImageField(default='images/img.jpg', upload_to='images/'),
        ),
    ]
