# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0015_auto_20170917_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='gymEmail',
            field=models.EmailField(default=1, max_length=100, verbose_name='Email ID'),
            preserve_default=False,
        ),
    ]
